name: Move new issues into Triage

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Fetch Quest Fall 2024 Project
          column: In Progress
          repo-token: ${{ secrets.MOVE_ASSIGNED_TASKS_TOKEN }}
